
version: "3.7"
services:
  database_estoque:
    image: postgres
    container_name: database_estoque
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=estoque
      - POSTGRE_DB=estoque
    volumes:
      - pgdata:/data/postgres
    build:
      context: .
      network: host
  app:
    build:
      context: .
      network: host
    container_name: api_estoque
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
volumes:
  pgdata:
    driver: local


